### ISSUE TITLE
Environment Variables Issue on Fresh Install

### ISSUE THREAD

**Issue by AndrewIOM** [Prodiguer/synda#1]
Hi there, I get the following issue with the current install script, on a fresh Ubuntu 14.04 instance with the only modification the install of the prereqs:

running install_egg_info
Writing /home/x/sdt/lib/python2.7/site-packages/sdt-3.0-py2.7.egg-info
/home/azureuser/garbage/sdt-3.0
Traceback (most recent call last):
  File "/home/x/sdt/bin/synda", line 21, in <module>
    import sdconst
  File "/home/x/sdt/lib/sd/sdconst.py", line 12, in <module>
    import sdapp
  File "/home/x/sdt/lib/sd/sdapp.py", line 22, in <module>
    import sdconfig
  File "/home/x/sdt/lib/sd/sdconfig.py", line 65, in <module>
    raise SDException('SDCONFIG-010',"'ST_HOME' is not set")
sdexception.SDException: code=SDCONFIG-010,message='ST_HOME' is not set

Adding ST_HOME manually fixes the problem.

**Comment by jripsl** [comment]
Hi AndrewIOM,
Fixed. It was a bug in the installer.
Thanks for the feedback.
