### ISSUE TITLE
Error : "duplicate column name: selection_file_checksum"

### ISSUE THREAD

**Issue by senesis** [Prodiguer/synda#119]
After a fresh DEB ubuntu16 install (on Ubuntu 16.04 LTS) , my first trial leads to that error :

root@pavilion-stephane:~# synda search atmos tas CMIP5

*** Error occured at 2019-07-24 14:58:35.197236 ***

Traceback (most recent call last):
  File "/usr/bin/synda", line 130, in <module>
    stream=syndautils.get_stream(subcommand=args.subcommand,parameter=args.parameter,selection_file=args.selection_file,no_default=args.no_default)
  File "/usr/share/python/synda/sdt/bin/syndautils.py", line 34, in get_stream
    import sdbuffer, sdparse, sdstream, sdconfig, sddeferredbefore, sdexception
  File "/usr/share/python/synda/sdt/bin/sdbuffer.py", line 20, in <module>
    from sdtypes import Buffer
  File "/usr/share/python/synda/sdt/bin/sdtypes.py", line 25, in <module>
    import sdmts
  File "/usr/share/python/synda/sdt/bin/sdmts.py", line 25, in <module>
    import sddbpagination
  File "/usr/share/python/synda/sdt/bin/sddbpagination.py", line 26, in <module>
    import sddb
  File "/usr/share/python/synda/sdt/bin/sddb.py", line 148, in <module>
    sddbversion.check_version(conn) # this call upgrade the database schema if database version does not match binary version
  File "/usr/share/python/synda/sdt/bin/sddbversion.py", line 47, in check_version
    upgrade_db(conn,current_db_version,sdapp.version)
  File "/usr/share/python/synda/sdt/bin/sddbversion.py", line 59, in upgrade_db
    upgrade_procs[v](conn)
  File "/usr/share/python/synda/sdt/bin/sddbversion.py", line 92, in upgrade_35
    conn.execute("alter table history add column selection_file_checksum TEXT")
OperationalError: duplicate column name: selection_file_checksum
root@pavilion-stephane:~# whoami
root

**Comment by senesis** [comment]
Version 3.10 solved the issue
