### ISSUE TITLE
selection of multiple variables in CMIP6

### ISSUE THREAD

**Issue by francocatalano** [Prodiguer/synda#148]
Hi,
Setting multiple variables in the selection file, like:
project=CMIP6
source_id=EC-Earth3
experiment_id=historical ssp126 ssp585
member_id=r1i1p1f1
variable[table_id=Amon]=tas psl pr hfls hfss evspsbl rlds rlus rsds rsus prw
variable[table_id=Lmon]=mrro mrso mrsos
variable[table_id=LImon]=snc snd

result in the following error:
synda search -s selection/myselfile.txt 

*** Error occured at 2020-06-10 13:10:01.611581 ***

Traceback (most recent call last):
  File "/dove/franco/miniconda/miniconda2/envs/franco-synda-environment/bin/synda", line 11, in <module>
    sys.exit(run())
  File "/fas_c/UTENTI/franco/miniconda/miniconda2/envs/franco-synda-environment/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/synda.py", line 167, in run
    status=sdtsaction.actions[args.subcommand](args)
  File "/fas_c/UTENTI/franco/miniconda/miniconda2/envs/franco-synda-environment/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtsaction.py", line 85, in search
    dataset_search(args)
  File "/fas_c/UTENTI/franco/miniconda/miniconda2/envs/franco-synda-environment/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtsaction.py", line 210, in dataset_search
    datasets=sdrdataset.get_datasets(stream=args.stream,dry_run=args.dry_run)
  File "/fas_c/UTENTI/franco/miniconda/miniconda2/envs/franco-synda-environment/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdrdataset.py", line 38, in get_datasets
    result=sdquicksearch.run(stream=stream,parameter=parameter,post_pipeline_mode=post_pipeline_mode,dry_run=dry_run)
  File "/fas_c/UTENTI/franco/miniconda/miniconda2/envs/franco-synda-environment/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdquicksearch.py", line 51, in run
    queries=sdpipeline.build_queries(stream=stream,path=path,parameter=parameter,index_host=index_host,parallel=False,load_default=False)
  File "/fas_c/UTENTI/franco/miniconda/miniconda2/envs/franco-synda-environment/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdpipeline.py", line 85, in build_queries
    queries=sdquerypipeline.run(stream,index_host=index_host,query_type=query_type,dry_run=dry_run,parallel=parallel)
  File "/fas_c/UTENTI/franco/miniconda/miniconda2/envs/franco-synda-environment/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdquerypipeline.py", line 43, in run
    facets_groups=sdparampipeline.run(facets_groups)
  File "/fas_c/UTENTI/franco/miniconda/miniconda2/envs/franco-synda-environment/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdparampipeline.py", line 51, in run
    facets_groups=sdlocal2remote.run(facets_groups)
  File "/fas_c/UTENTI/franco/miniconda/miniconda2/envs/franco-synda-environment/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdlocal2remote.py", line 44, in run
    del local_name_rules['frequency']
KeyError: 'frequency'

The sample selection files work well even with multiple variables but they are all for CMIP5. I am quite new to synda. Am I doing something wrong?
Thanks

**Comment by francocatalano** [comment]
Thanks @painter1 Unfortunately, separating names with commas did not solve the problem. And I could not find additional information in log/discovery.log.
So far, I have been able to download the data only by creating a separate file for each table_id. That is, only one "variable" line per selection file.

**Comment by YanchunHe** [comment]
It works for me like this:

```
project=CMIP6
variant_label=r1i1p1f1
source_id=NorESM2-LM,CESM2,EC-Earth3,HadGEM3-GC31-LM,GFDL-CM4,MRI-ESM2-0
experiment_id=historical,1pctCO2
table_id=Amon,Omon
variable_id=tas
variable_id=tos
grid_label=gn
latest=true
```

Although this may be not accurate.

**Comment by pjournou-ipsl** [comment]
Thanks to Yanchun He.

The proposed solution works (note that commas or blanks are supported as separator).

The syntax of the "variable[table_id=Amon]=tas" expression is not correct.

A selection file accepts only the four following templates as line formats :
        `variable[<realm>][<frequency>]=<variable1> <variable2> [...]`
        `variable[<facet1> <facet2> <facet3> [...]]=<variable1> <variable2> [...]`
        `<name>=<value>`
        `<value>`
