### ISSUE TITLE
No option 'destination_directory' in section: 'globustransfer'

### ISSUE THREAD

**Issue by stefsmeets** [Prodiguer/synda#154]
Hi, I'm getting an error using Synda with default parameters. I'm not even using globustransfer, but it crashes when it cannot find `destination_directory`. It seems that Synda is looking for a variable that does not exist. As a work-around, I just added a dummy variable `destination_directory` to `sdt.conf`. 

The tracelog can be found below:

```Traceback (most recent call last):
  File "/home/stef/bin/synda", line 11, in <module>
    sys.exit(run())
  File "/home/stef/miniconda3/envs/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/synda.py", line 178, in run
    status=sdtiaction.actions[args.subcommand](args)
  File "/home/stef/miniconda3/envs/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtiaction.py", line 213, in get
    import sdlogon, sdrfile, sddeferredafter, sddirectdownload, syndautils, humanize, sdconfig, os, sdconst, sdearlystreamutils
  File "/home/stef/miniconda3/envs/synda/bin/sddirectdownload.py", line 4, in <module>
    __import__('pkg_resources').run_script('synda==3.10', 'sddirectdownload.py')
  File "/home/stef/miniconda3/envs/synda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/stef/miniconda3/envs/synda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/stef/miniconda3/envs/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sddirectdownload.py", line 23, in <module>
    import sdglobus
  File "/home/stef/miniconda3/envs/synda/bin/sdglobus.py", line 4, in <module>
    __import__('pkg_resources').run_script('synda==3.10', 'sdglobus.py')
  File "/home/stef/miniconda3/envs/synda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/stef/miniconda3/envs/synda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/home/stef/miniconda3/envs/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdglobus.py", line 115, in <module>
    dst_directory = sdconfig.config.get("globustransfer", "destination_directory")
  File "/home/stef/miniconda3/envs/synda/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'destination_directory' in section: 'globustransfer'
```

**Comment by pjournou-ipsl** [comment]
I was not in the team, in Aug 2020...  Nevertheless, I saw that in the code there was a 'destination_endpoint' and in the sdt.conf a destination_directory one. To help, I would have suggested to update the name of the sdt.conf parameter... Perhaps this would have fixed the problem...
 
But, at the moment, all Globus transfer features have been deprecated, so this issue will be closed. 
Thank you for your understanding.
