### ISSUE TITLE
synda remove fails to import sdsimplefilter

### ISSUE THREAD

**Issue by clairbarnes** [Prodiguer/synda#185]
Hi,

I'm trying to `synda remove rcm_name=HadREM3-GA7-05` (for example), and I get the error 
```
Traceback (most recent call last):
  File "/usr/local/bin/Anaconda3/envs/synda/bin/synda", line 33, in <module>
    sys.exit(load_entry_point('synda==3.34', 'console_scripts', 'synda')())
  File "/usr/local/bin/Anaconda3/envs/synda/lib/python3.8/site-packages/synda/sdt/main.py", line 196, in run
    status = sdtiaction.actions[args.subcommand](args)
  File "/usr/local/bin/Anaconda3/envs/synda/lib/python3.8/site-packages/synda/sdt/sdtiaction.py", line 447, in remove
    return sdremove.run(args,stream)
  File "/usr/local/bin/Anaconda3/envs/synda/lib/python3.8/site-packages/synda/sdt/sdremove.py", line 36, in run
    run_remote(args,stream)
  File "/usr/local/bin/Anaconda3/envs/synda/lib/python3.8/site-packages/synda/sdt/sdremove.py", line 84, in run_remote
    remove_helper(args,metadata)
  File "/usr/local/bin/Anaconda3/envs/synda/lib/python3.8/site-packages/synda/sdt/sdremove.py", line 87, in remove_helper
    import humanize, sdsimplefilter, sdconst, sdutils
ModuleNotFoundError: No module named 'sdsimplefilter'
```
This module seems to be part of the `synda` package and not something I can install myself - any suggestions?

Thanks,

Clair

**Comment by AtefBN** [comment]
Hello Clair,
I have duplicated the same behavior on our dev environment, I'll investigate the issue and let you know when we have a fix for this.
Sorry for the inconvenience.

**Comment by AtefBN** [comment]
Hi Clair, as mentionned above, the latest release (3.35) pushed by Patrice on conda resolves this issue. 
I'll be marking this issue as closed but if any persistent issues rise up feel free to reopen it. 
Cheers
