### ISSUE TITLE
Unhandled exceptions stopping daemon from running continuously

### ISSUE THREAD

**Issue by AndrewIOM** [Prodiguer/synda#2]
Hi there, another question! When processing a fairly large download queue, I get an unhandled exception within 5-60 minutes of starting the daemon. I'm not sure if this is a problem with ESGF nodes or within Synda. The stack trace is:

Traceback (most recent call last):
  File "/home/azureuser/sdt/lib/sd/sdworkerutils.py", line 32, in run
    self._service.run(self._instance)
  File "/home/azureuser/sdt/lib/sd/sddownload.py", line 31, in run
    cls.start_transfer_script(tr)
  File "/home/azureuser/sdt/lib/sd/sddownload.py", line 39, in start_transfer_script
    sdlogon.renew_certificate(False)
  File "/home/azureuser/sdt/lib/sd/sdlogon.py", line 46, in renew_certificate
    (hostname,port,username)=sdopenid.extract_info_from_openid(openid)
  File "/home/azureuser/sdt/lib/sd/sdopenid.py", line 33, in extract_info_from_openid
    xrds_buf=sdnetutils.HTTP_GET(openid)
  File "/home/azureuser/sdt/lib/sd/sdnetutils.py", line 129, in HTTP_GET
    raise SDException(errcode,errmsg)
SDException: code=SDNETUTI-002,message=HTTP query failed (url=https://esgf-node.ipsl.fr/esgf-idp/openid/XXXXXXX,exception=<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)

I also tried an OpenID registered at pcmdi9.llnl.gov/ but also get an exception every so often:

Traceback (most recent call last):
  File "/home/azureuser/sdt/lib/sd/sdworkerutils.py", line 32, in run
    self._service.run(self._instance)
  File "/home/azureuser/sdt/lib/sd/sddownload.py", line 31, in run
    cls.start_transfer_script(tr)
  File "/home/azureuser/sdt/lib/sd/sddownload.py", line 39, in start_transfer_script
    sdlogon.renew_certificate(False)
  File "/home/azureuser/sdt/lib/sd/sdlogon.py", line 46, in renew_certificate
    (hostname,port,username)=sdopenid.extract_info_from_openid(openid)
  File "/home/azureuser/sdt/lib/sd/sdopenid.py", line 33, in extract_info_from_openid
    xrds_buf=sdnetutils.HTTP_GET(openid)
  File "/home/azureuser/sdt/lib/sd/sdnetutils.py", line 129, in HTTP_GET
    raise SDException(errcode,errmsg)
SDException: code=SDNETUTI-002,message=HTTP query failed (url=https://pcmdi9.llnl.gov/esgf-idp/openid/XXXXX,exception=('The read operation timed out',))

**Comment by jripsl** [comment]
Hi AndrewIOM,
It seems that there is a problem with the renewal of your certificate.
To debug this issue, you can test the certificate renewal manually with "synda certificate renew" command. It the certificate renewal failed randomly, it is more likely that the problem is on the server side. 
The second problem is indeed the unhandled exception, resulting in stacktrace instead of log.
I just fixed the later problem in synda testing release (3.1).
(to install testing release, you can use "./install.sh -d 3.1" command)
Thanks for your feedback

**Comment by AndrewIOM** [comment]
Hi, many thanks for the rapid patch, it seems to have fixed the issues on my install! I can renew the certificate using the renew command, so it just seems to be sometimes the remote server has some hiccups.

This is a really great app! Thanks, Andy
