### ISSUE TITLE
daemon stops when certificate error occurs

### ISSUE THREAD

**Issue by ghost** [Prodiguer/synda#27]
In daemon mode, when certificate error occurs, the daemon is stopped

Example

traceback file is:

```
Traceback (most recent call last):
  File "/home/synda/sdt/lib/sd/sdworkerutils.py", line 33, in run
    self._service.run(self._instance)
  File "/home/synda/sdt/lib/sd/sddmdefault.py", line 40, in run
    cls.start_transfer_script(tr)
  File "/home/synda/sdt/lib/sd/sddmdefault.py", line 48, in
start_transfer_script
    sdlogon.renew_certificate(False)
  File "/home/synda/sdt/lib/sd/sdlogon.py", line 87, in renew_certificate
    (hostname,port,username)=sdopenid.extract_info_from_openid(openid)
  File "/home/synda/sdt/lib/sd/sdopenid.py", line 42, in
extract_info_from_openid
    raise OpenIDProcessingException('SDOPENID-002','Error occured while
processing OpenID')
OpenIDProcessingException: code=SDOPENID-002,message=Error occured while
processing OpenID
```

transfer.log is

```
2016-06-06 00:36:04,131 DEBUG SYDEVENT-001 'file_complete_event' triggered (
cmip5.output1.MIROC.MIROC-ESM.piControl.mon.ocean.Omon.r1i1p1.v20120608.thkcello_Omon_MIROC-ESM_piControl_r1i1p1_206001-206912.nc
)
2016-06-06 00:36:12,140 ERROR SDOPENID-200 Error occured while processing
OpenID (code=SDNETUTI-002,message=HTTP query failed (url=
https://pcmdi.llnl.gov/esgf-idp/openid/elidart,exception=<urlopen error
timed out>,timeout=10))
2016-06-06 00:36:12,140 ERROR SDDMDEFA-502 Exception occured while
retrieving certificate (code=SDOPENID-002,message=Error occured while
processing OpenID)
2016-06-06 00:36:12,140 ERROR SDWUTILS-002 Thread didn't complete
successfully
2016-06-06 00:36:13,142 ERROR SDOPENID-200 Error occured while processing
OpenID (code=SDNETUTI-002,message=HTTP query failed (url=
https://pcmdi.llnl.gov/esgf-idp/openid/elidart,exception=<urlopen error
timed out>,timeout=10))
2016-06-06 00:36:13,142 ERROR SDDMDEFA-502 Exception occured while
retrieving certificate (code=SDOPENID-002,message=Error occured while
processing OpenID)
2016-06-06 00:36:13,142 ERROR SDWUTILS-002 Thread didn't complete
successfully
2016-06-06 00:36:14,155 ERROR SDTSCHED-002 Fatal exception occured during
download
2016-06-06 00:36:14,155 INFO SDTSCHED-901 Scheduler successfully stopped
2016-06-06 00:36:14,155 INFO SDDAEMON-034 Daemon stopped
```

The selection file is

```
#######################
project="CMIP5"
institute="MIROC"
model="MIROC-ESM"
experiment="piControl"
data_node="aims3.llnl.gov"
protocol=gridftp
time_frequency="mon"
latest=true
replica=false
#######################
```

A better behaviour would be to keep the daemon running, stop starting new download, and retry certificate renewal at a given interval.

**Comment by pjournou-ipsl** [comment]
In the future 3.4 release, the features based on the daemon will be deprecated. A new feature for asynchronous downloads will be implemented.
