### ISSUE TITLE
pkg_resources.DistributionNotFound: setuptools>=1.0

### ISSUE THREAD

**Issue by jripsl** [Prodiguer/synda#28]
```
        Traceback (most recent call last):
          File "/usr/share/python/synda/sdt/bin/myproxyclient", line 5, in <module>
            from pkg_resources import load_entry_point
          File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/pkg_resources.py", line 3025, in <module>
            parse_requirements(__requires__), Environment()
          File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/pkg_resources.py", line 628, in resolve
            raise DistributionNotFound(req)
        pkg_resources.DistributionNotFound: setuptools>=1.0
```

**Comment by jripsl** [comment]
setuptools version is too old

Fixed with:

pip install setuptools==19.7
