### ISSUE TITLE
No module named datetime

### ISSUE THREAD

**Issue by matteodefelice** [Prodiguer/synda#42]
Ubuntu 15.10 here. 
I've installed synda from the repository, set up my ESGF credentials and when I tried a perform a search (copying one of the examples on the README) I get: 

```
matteo@matteo-dell:~/work/ECEMWP3$ synda search cmip5 output1 MOHC HadGEM2-A amip4xCO2 mon atmos Amon r1i1p1
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/python/synda/sdt/bin/sdapputils.py", line 27, in print_exception
    import os,sys,traceback,datetime # note: those imports must be done here (i.e. it doesn't work if done top of the file)
ImportError: No module named datetime

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/synda", line 123, in <module>
    stream=syndautils.get_stream(args)
  File "/usr/share/python/synda/sdt/bin/syndautils.py", line 32, in get_stream
    import sdbuffer, sdparse, sdstream, sdconfig, sddeferredbefore, sdexception
  File "/usr/share/python/synda/sdt/bin/sdstream.py", line 18, in <module>
    import sddquery
  File "/usr/share/python/synda/sdt/bin/sddquery.py", line 20, in <module>
    import sdutils
  File "/usr/share/python/synda/sdt/bin/sdutils.py", line 20, in <module>
    import datetime
ImportError: No module named datetime
```

**Comment by jripsl** [comment]
Is this helping ?

sudo cp /usr/bin/python /usr/bin/python2.7 /usr/bin/python2 /usr/share/python/synda/sdt/bin

(from http://askubuntu.com/questions/509283/python-no-module-named-datetime)

**Comment by matteodefelice** [comment]
That was the first solution that come up to my mind but it didn't work, now I don't have the output because meanwhile I have moved to another way to deal with ESGF data but I'll try again asap to give you a feedback, thank you
