### ISSUE TITLE
Improve error message when connection fails 

### ISSUE THREAD

**Issue by jripsl** [Prodiguer/synda#50]
Improve error display in this case (remove stacktrace):

```
$ sudo /usr/share/python/synda/sdt/bin/sdppproxy.py

    *** Error occured at 2016-07-05 10:51:15.909778 ***

    Traceback (most recent call last):
      File "/usr/share/python/synda/sdt/bin/sdppproxy.py", line 76, in <module>
        print get_service().test1(1,2)
      File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/pyjsonrpc/http.py", line 162, in __call__
        return self.http_client_instance.call(self.method, *args, **kwargs)
      File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/pyjsonrpc/http.py", line 253, in call
        debug = self.debug
      File "/usr/share/python/synda/sdt/lib/python2.6/site-packages/pyjsonrpc/http.py", line 131, in http_request
        response = urllib2.urlopen(request, timeout = timeout)
      File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib64/python2.6/urllib2.py", line 391, in open
        response = self._open(req, data)
      File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
        '_open', req)
      File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
        result = func(*args)
      File "/usr/lib64/python2.6/urllib2.py", line 1198, in https_open
        return self.do_open(httplib.HTTPSConnection, req)
      File "/usr/lib64/python2.6/urllib2.py", line 1165, in do_open
        raise URLError(err)
    URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by jripsl** [comment]
Done in 3.7
